### ISSUE TITLE
gapi is not defined

### ISSUE THREAD

**Issue by gabrielrojasp** [miltador/angular-google-signin#21]
Hi,

The example works fine, but if I'm reflesh page generated this error.

zone.js:518 ReferenceError: gapi is not defined
    at GoogleSignInComponent.auth2Init (index.ts:88)
    at GoogleSignInComponent.ngAfterViewInit (index.ts:80)

Can you help me?

Thanks

**Comment by edelfrade** [comment]
take out the 'defer' from the script tag 

<script src="https://apis.google.com/js/platform.js"></script>
 EDITED: as @miltador cleared, import the script without defer or async, just the src and give it a try

**Comment by gabrielrojasp** [comment]
I have the same 👍 
<script src="https://apis.google.com/js/platform.js" async defer></script>
but don't work

thanks for reaply

**Comment by miltador** [comment]
Have you tried to take out `defer` and `async` attributes from `script` tag (as @ernerock suggests)?
Also make sure that this line is included before your app js.

**Comment by srushtipatel07** [comment]
its working 
thnks

**Comment by Klerith** [comment]
Just this add this
```
<script src="https://apis.google.com/js/platform.js"></script>
```

**Comment by gabrielrojasp** [comment]
works fine ! thanks

**Comment by montaserfzy** [comment]
Works for me, Thanks @ernerock

**Comment by mhaby143** [comment]
Now it works fine. but can i ask something? what's the use of 'defer' and 'async'?

**Comment by edelfrade** [comment]
Defer tells the script to load after that page has finished parsing. Async tells it to load asynchronously with the rest of the page, making it non-blocking. These are usually good practices since script tags on the head prevent the page from continuing loading until it has loaded said scrip tag. In this case you need to prevent the page from continuing parsing so the global variable gets defined by the script. Ideally the scrip would be loaded within the module with a callback or similar initialization method to prevent all this from happening.

**Comment by montaserfzy** [comment]
this is the different 
![async-defer](https://user-images.githubusercontent.com/8565425/51282919-28914d00-19ef-11e9-94d2-03b658a0cb9e.png)
